# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff5e5e91e7b1fc9d1fd4f945158a938916b8431d7925ada19830b195c78e3e9323bec9f3307362b448034b783b5ccf4a78c08fa28dcd77d35129aef82adae360

test:
  secret_key_base: 1a52911e3f5a9b60295b9c3789e0f351c5e9e575cf8307da595a51a7fd5ffa35069cfe7b2921e2cee63171ba700b6268fb2148340009cbcc2d9151a7b3c6b770

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
